# Configurações do PostgreSQL
# O final da URL é o NOME DO BANCO que você criou
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres2
# O username é a CHAVE (o usuário que você resetou a senha no terminal)
spring.datasource.username=postgres
spring.datasource.password=rpp96320

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
server.address=0.0.0.0