# Configuracoes do PostgreSQL
# O final da URL e o NOME DO BANCO que voce criou
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres2
# O username e a CHAVE (o usuario que voce resetou a senha no terminal)
spring.datasource.username=postgres
spring.datasource.password=rpp96320

# Configuracoes do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
server.address=0.0.0.0